services:
  - type: web
    name: exact-match-portfolio
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve dist/client -s -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
